### ISSUE TITLE
Great-circle distance

### ISSUE THREAD

**Issue by roboes** [michaeldorman/nngeo#10]
Hi,

Is there a way to define the distance calculation methodology, i.e. "Great Circle", "Euclidian", etc., similar to the `which` argument under `sf::st_distance`?

**Comment by michaeldorman** [comment]
Hi,

Choosing the distance method in `st_nn` is not supported at the moment. When the input data are in lon-lat then great circle distances are calculated, with projected data euclidean distances are calculated. One more option, in case you need euclidean distances for lon-lat data, is to set the CRS to `NA`:

```r
st_set_crs(x, NA)
```

I wonder in which case could it be useful to find nearest neighbours according to the other methods given in `st_distance` (Hausdorff or Frechet), will be happy to hear about your use case if you can elaborate please. 

Thanks!

**Comment by roboes** [comment]
Dear Michael,

Thank you for your prompt response. Sorry for my question, I am a little unaware of the distance method used in my data in `st_nn`.

Using `sf::st_read` I imported [this](https://www2.census.gov/geo/tiger/GENZ2018/shp/cb_2018_us_zcta510_500k.zip) shapefile for the US:

`shapefile_us <- sf::st_read(dsn = "Shapefile", layer = "cb_2018_us_zcta510_500k")`

Retrieving the Coordinate Reference System (CRS), I get the following result:

`st_crs(shapefile_us)`
Coordinate Reference System:
  EPSG: 4269 
  proj4string: "+proj=longlat +datum=NAD83 +no_defs"

An every variable that I have the latitude and longitude information I turn it into a `sf` object with the `shapefile_us` CRS reference, e.g.: `st_as_sf(coords = c("longitude", "latitude"), crs = st_crs(shapefile_us))`.

Does this mean that if I did the distance calculation to the nearest point using `st_nn`, it is calculating the distances using the "Great Circle" methodology?

Many thanks for your support!

**Comment by michaeldorman** [comment]
That's correct, these data are in lon-lat, therefore the great circle distances are used. In fact, since at least one of the layers is lines or polygons, then `st_nn` uses `st_distance` to calculate the distances. You can see in the following example that the distances returned by `st_distance` and `st_nn` are identical. These are two specific polygons in New-York and Boston, so the distance of ~300 km makes sense.

```r
library(sf)

x = st_read("cb_2018_us_zcta510_500k.shp")
## Reading layer `cb_2018_us_zcta510_500k' from data source `/home/michael/Downloads/cb_2018_us_zcta510_500k/cb_2018_us_zcta510_500k.shp' using driver `ESRI Shapefile'
## Simple feature collection with 33144 features and 5 fields
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: -176.6847 ymin: -14.37374 xmax: 145.8304 ymax: 71.34122
## epsg (SRID):    4269
## proj4string:    +proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs

a = x[x$GEOID10 == "10171", ]
b = x[x$GEOID10 == "02141", ]

st_distance(a, b)
## Units: [m]
##          [,1]
## [1,] 299389.1

library(nngeo)

st_nn(a, b, returnDist = TRUE)
## lines or polygons
##   |======================================================================| 100%
## $nn
## $nn[[1]]
## [1] 1
## 
## 
## $dist
## $dist[[1]]
## [1] 299389.1
```

**Comment by roboes** [comment]
Great, thank you for the explanation!
