### ISSUE TITLE
question: what replaces the raster_* function?

### ISSUE THREAD

**Issue by rgzn** [michaeldorman/nngeo#11]
The latest versions have removed functions such as `raster_extract`.  What is the best practice for replacing them?

**Comment by michaeldorman** [comment]
Hi, 

All the `raster_*` functions were moved to another package named `geobgu`, which is on GitHub, in order to make `nngeo` independent of `raster`. I'm sorry for the confusion.

Here is a reproducible example of `raster_extract`:

``` r
library(stars)
# devtools::install_github("michaeldorman/geobgu")
library(geobgu)

# Sample points
set.seed(3)
pnt = st_sample(st_as_sfc(st_bbox(dem)), 5)
pnt = st_sf(pnt)
pnt
```

    ## Simple feature collection with 5 features and 0 fields
    ## geometry type:  POINT
    ## dimension:      XY
    ## bbox:           xmin: 689360.6 ymin: 3629132 xmax: 690108.8 ymax: 3629633
    ## epsg (SRID):    32636
    ## proj4string:    +proj=utm +zone=36 +ellps=WGS84 +units=m +no_defs
    ##                        pnt
    ## 1 POINT (689360.6 3629607)
    ## 2 POINT (690108.8 3629132)
    ## 3 POINT (689614.4 3629300)
    ## 4 POINT (689547.4 3629580)
    ## 5 POINT (689868.5 3629633)

``` r
# Extract
pnt$elevation = raster_extract(dem, pnt)
pnt
```

    ## Simple feature collection with 5 features and 1 field
    ## geometry type:  POINT
    ## dimension:      XY
    ## bbox:           xmin: 689360.6 ymin: 3629132 xmax: 690108.8 ymax: 3629633
    ## epsg (SRID):    32636
    ## proj4string:    +proj=utm +zone=36 +ellps=WGS84 +units=m +no_defs
    ##                        pnt elevation
    ## 1 POINT (689360.6 3629607)       203
    ## 2 POINT (690108.8 3629132)        95
    ## 3 POINT (689614.4 3629300)       188
    ## 4 POINT (689547.4 3629580)       139
    ## 5 POINT (689868.5 3629633)        64

``` r
# Plot
plot(dem, text_values = TRUE, col = terrain.colors(11), reset = FALSE)
plot(st_geometry(pnt), add = TRUE, pch = 16, col = "red")
text(st_coordinates(pnt), as.character(pnt$elevation), col = "red", pos = 3, font = 2)
```

![unnamed-chunk-1-1](https://user-images.githubusercontent.com/9386655/72414932-06eeb100-377c-11ea-8aea-2fe136462c9a.png)

Best regards,

Michael

**Comment by rgzn** [comment]
thanks!
