### ISSUE TITLE
Is it possible to set an option to run on multiple CPUs or GPUs?

### ISSUE THREAD

**Issue by emilmahler** [michaeldorman/nngeo#13]
For large amounts of data, many of this package's functions are quite slow. Is it possible to pass a flag to the underlying C++ to split the task up and utilize all available CPU cores? Right now it runs single threaded.

**Comment by michaeldorman** [comment]
Thanks, I now added a `parallel` parameter in `st_nn`. 

Here is a reproducible example comparing `parallel=1` (single thread) with `parallel=4` (parallel with four cores). The processing time is reduced from ~20 seconds to ~5 seconds:

``` r
# devtools::install_github("michaeldorman/nngeo")
library(nngeo)

# Sample polygon layer
set.seed(1)
n = 150
x = data.frame(
  lon = (runif(n) * 2 - 1) * 70,
  lat = (runif(n) * 2 - 1) * 70
)
x = st_as_sf(x, coords = c("lon", "lat"), crs = 4326)
x = st_transform(x, 32630)
x = st_buffer(x, 1000000)

# Single thread
start = Sys.time()
result1 = st_nn(x, x, k = 3, progress = FALSE)
end = Sys.time()
end - start
```

    ## Time difference of 20.81732 secs

``` r
# Parallel with 4 cores
start = Sys.time()
result2 = st_nn(x, x, k = 3, progress = FALSE, parallel = 4)
end = Sys.time()
end - start
```

    ## Time difference of 5.431549 secs

``` r
# Compare results
all.equal(result1, result2)
```

    ## [1] TRUE

Will be happy to hear if you encounter any issues with this, or if there are other functions where this may be useful.

**Comment by emilmahler** [comment]
Thank you. This is amazing. My dataset is huge and can take days to churn through. Here are some quick results with your new package:

`start_time <- Sys.time()`
`result_1 <- st_connect(centroids_10000,polylines_10000,parallel=1)`
`Sys.time() - start_time # Time difference of 1.002905 hours`
  
`start_time <- Sys.time()`
`result_2 <- st_connect(centroids_10000,polylines_10000,parallel=24)`
`Sys.time() - start_time # Time difference of 4.157856 mins`

**Comment by michaeldorman** [comment]
Great, glad to hear!
