### ISSUE TITLE
A few typos/missing words in `st_nn`

### ISSUE THREAD

**Issue by everydayduffy** [michaeldorman/nngeo#14]
Hi,

Thanks for making a great package! I'm using version 0.3.4. 

The `sparse` argument in `st_nn` has an unfinished sentence in the help file. 

The `progress` argument is missing a bracket and maybe more words - not sure. 

Only very minor things, but thought I would point them out.

**Comment by michaeldorman** [comment]
Thank you very much, it's fixed now!
