### ISSUE TITLE
Distance result when parallel parameter is larger than 1

### ISSUE THREAD

**Issue by heejinkim16** [michaeldorman/nngeo#15]
Thank you very much for the amazing package! 

I just have a quick question on the distance result of st_nn after setting the parallel parameter larger than 1. It seems that the result in $dist is the same as $nn. 

I first tried st_nn with the example data (cities and water) to calculate distance without parallel processing. Below are the code.

```
library(nngeo)
library(parallel)
nn = st_nn(cities, water, returnDist = TRUE, progress = TRUE)
```
> [[1]]
> [1] 3
>  
> [[2]]
> [1] 2
> 
> [[3]]
> [1] 2

```
nn$dist
```

> [[1]]
> [1] 22833.09
> 
> [[2]]
> [1] 1372.235
> 
> [[3]]
> [1] 2777.558

However, the distance result changes when I add parallel = 4

```
nn_p2 = st_nn(cities, water, returnDist = TRUE, progress = TRUE, parallel = 4)
nn_p2 $nn
```

> [[1]]
> [1] 3
> 
> [[2]]
> [1] 2
> 
> [[3]]
> [1] 2

```
nn_p2$dist
```

> [[1]]
> [1] 3
>  
> [[2]]
> [1] 2
>  
> [[3]]
> [1] 2

I hope I did not ask the same question already covered. Could you let me know if I miss anything here?

**Comment by michaeldorman** [comment]
Thanks! This looks like a bug in the "parallel>1" method, I'll check and get back to you as soon as possible.

**Comment by michaeldorman** [comment]
Indeed this was a bug, the `nn` and `dist` parts were identical when `parallel>1`. Thank you for letting me know! 

Should be fixed now:

```r
library(nngeo)
nn_p2 = st_nn(cities, water, returnDist = TRUE, progress = TRUE, parallel = 4)
## lines or polygons
nn_p2
## $nn
## $nn[[1]]
## [1] 3
## 
## $nn[[2]]
## [1] 2
## 
## $nn[[3]]
## [1] 2
## 
## 
## $dist
## $dist[[1]]
## [1] 22833.09
## 
## $dist[[2]]
## [1] 1372.235
## 
## $dist[[3]]
## [1] 2777.558
```

in the development version, which you can install with:

```r
remotes::install_github("michaeldorman/nngeo")
```
