### ISSUE TITLE
Performance of st_nn with lines or polygons

### ISSUE THREAD

**Issue by mem48** [michaeldorman/nngeo#16]
Hi,

Thanks for a great package. I've noticed that st_nn is very slow when getting the nearest lines to a point, and looking at the code it seems that it just defaults to using sf::st_distance from each point to all the lines.

I've been working on my own function to get around this problem, by measuring the nearest 10 centroids of the lines (which is fast), and then performing the st_nn on just those 10 lines rather than the whole dataset.

```
nn_line <- function(point, lines){
  cents <- sf::st_centroid(lines)
  nn <- nngeo::st_nn(point, cents, k = 10)

  res <- list()
  for(i in seq_len(nrow(point))){
    nnsub <- nn[[i]]
    sub <- unlist(nngeo::st_nn(point$geometry[i], lines$geometry[nnsub], progress = FALSE))
    res[[i]] <- nnsub[sub]
  }
  return(res)

}

```

This function is about 143x faster on my data, so I thought it might be useful to share more generally.

**Comment by michaeldorman** [comment]
Hi Malcolm,

Thank you very much, this is a very interesting idea! However, it's not guaranteed that lines whose centroid is nearest are also nearest when considering every possible point on the line. 

In the following (extreme) example, there is one line (row=11) whose centroid is furthest from the point, yet it is the nearest one in terms of point-line distance. Considering only those lines whose centroid is nearest (rows 1 to 10) incorrectly returns row=4 as the nearest line:

``` r
library(nngeo)

# Function
nn_line <- function(point, lines){
  cents <- sf::st_centroid(lines)
  nn <- nngeo::st_nn(point, cents, k = 10)

  res <- list()
  for(i in seq_len(nrow(point))){
    nnsub <- nn[[i]]
    sub <- unlist(nngeo::st_nn(point$geometry[i], lines$geometry[nnsub], progress = FALSE))
    res[[i]] <- nnsub[sub]
  }
  return(res)

}

# Sample data
x = '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[18.4130859375,36.59788913307022]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[18.720703125,35.71083783530009],[19.6875,35.88905007936091],[20.4345703125,35.92464453144099]]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[17.666015625,35.639441068973944],[18.6328125,35.42486791930558]]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[16.787109375,35.99578538642032],[17.2705078125,35.53222622770337]]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[18.1494140625,35.88905007936091],[19.599609375,36.27970720524017]]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[19.9072265625,35.60371874069731],[18.984375,35.92464453144099]]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[17.578125,35.817813158696616],[18.6328125,35.817813158696616]]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[17.2265625,36.31512514748051],[17.75390625,35.99578538642032]]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[19.0283203125,35.496456056584165],[17.885742187499996,35.35321610123823]]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[19.2919921875,35.35321610123823],[18.544921875,35.35321610123823]]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[16.918945312499996,36.13787471840729],[17.490234375,36.03133177633187]]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[15.2490234375,37.16031654673677],[37.08984375,35.10193405724606]]}}]}'
dat = st_read(x)
```

    ## Reading layer `OGRGeoJSON' from data source `{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[18.4130859375,36.59788913307022]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[18.720703125,35.71083783530009],[19.6875,35.88905007936091],[20.4345703125,35.92464453144099]]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[17.666015625,35.639441068973944],[18.6328125,35.42486791930558]]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[16.787109375,35.99578538642032],[17.2705078125,35.53222622770337]]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[18.1494140625,35.88905007936091],[19.599609375,36.27970720524017]]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[19.9072265625,35.60371874069731],[18.984375,35.92464453144099]]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[17.578125,35.817813158696616],[18.6328125,35.817813158696616]]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[17.2265625,36.31512514748051],[17.75390625,35.99578538642032]]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[19.0283203125,35.496456056584165],[17.885742187499996,35.35321610123823]]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[19.2919921875,35.35321610123823],[18.544921875,35.35321610123823]]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[16.918945312499996,36.13787471840729],[17.490234375,36.03133177633187]]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[15.2490234375,37.16031654673677],[37.08984375,35.10193405724606]]}}]}' using driver `GeoJSON'
    ## Simple feature collection with 12 features and 0 fields
    ## geometry type:  GEOMETRY
    ## dimension:      XY
    ## bbox:           xmin: 15.24902 ymin: 35.10193 xmax: 37.08984 ymax: 37.16032
    ## geographic CRS: WGS 84

``` r
pnt = dat[1, ]
lines = dat[-1, ]

# Plot
plot(lines)
text(st_coordinates(st_centroid(lines)), rownames(lines))
plot(pnt, pch = 4, col = "red", add = TRUE)
```

![unnamed-chunk-1-1](https://user-images.githubusercontent.com/9386655/92966747-c10bf900-f480-11ea-92de-7c32fd822af2.png)

``` r
# Method 1
st_nn(pnt, lines)
```

    ## [[1]]
    ## [1] 11

``` r
# Method 2
nn_line(pnt, lines)
```

    ## [[1]]
    ## [1] 4

Even though this is an extreme example, still the function needs to accommodate this type of scenario. 

Thanks and Best regards,

Michael
