### ISSUE TITLE
st_nn() unit error for projection in US Survey feet/ftUS

### ISSUE THREAD

**Issue by Elieri** [michaeldorman/nngeo#22]
Seems like `st_nn()` may have an issue handling projections in US Survey feet/ftUS. When trying to use it for an sf object in EPSG:2248 (NAD83/Maryland), I get this error: 

```
x cannot convert ft into us
Did you try to supply a value in a context where a bare expression was expected?
```

It works fine when I transform to ESPG:4326, which is in meters.

New to R and to submitting issue reports, so let me know if you need more details, but it seems similar to this issue: https://github.com/r-spatial/sf/issues/504

**Comment by michaeldorman** [comment]
Thanks! Indeed it is similar to the `sf` issue you have mentioned. Please try installing the development version (https://github.com/michaeldorman/nngeo/commit/c0961499affe226428b5bc2b47dcf2a0af76be74):

```r
remotes::install_github("michaeldorman/nngeo")
```
 
and please let me know if the issue wasn't solved.
