### ISSUE TITLE
st_remove_holes Feature Renaming

### ISSUE THREAD

**Issue by njlyon0** [michaeldorman/nngeo#23]
Hi! I have been using the `st_remove_holes` function and absolutely loving it but I did notice a small modification that it was doing on the side: when I used this function it was renaming the "geometry" feature as "geom".

This is easily caught and fixed but I figured I could reach out and see if the feature renaming could be made optional (perhaps by setting the default to 'true' in case later `nngeo` functions anticipate a "geom" feature by name).

This example is not reproducible because I can't share the shapefile I used as "data1" but I hope it illustrates what I mean nonetheless.

Regardless, thanks for making a really useful function!

# Library call
library(tidyverse); library(nngeo)
#> Loading required package: sf
#> Linking to GEOS 3.10.1, GDAL 3.4.0, PROJ 8.2.0; sf_use_s2() is TRUE

# Check data structure
str(data1)
#> Classes ‘sf’ and 'data.frame':	15 obs. of  2 variables:
#>   $ uniqueID: chr  "UMR_I080.2M" "UMR_SG16.2C" "UMR_CH00.1M" "UMR_CN00.1M" ...
#> $ geometry:sfc_GEOMETRY of length 15; first list element: List of 1
#> ..$ : num [1:1907, 1:2] -90.5 -90.5 -90.5 -90.5 -90.5 ...
#> ..- attr(*, "class")= chr [1:3] "XY" "POLYGON" "sfg"
#> - attr(*, "sf_column")= chr "geometry"
#> - attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA
#> ..- attr(*, "names")= chr "uniqueID"

# Use nngeo::st_remove_holes()
data2 <- data1 %>%
  group_by(uniqueID) %>%
  nngeo::st_remove_holes()

# Re-check structure
str(data2)
#> Classes ‘sf’ and 'data.frame':	15 obs. of  2 variables:
#>   $ uniqueID: chr  "UMR_I080.2M" "UMR_SG16.2C" "UMR_CH00.1M" "UMR_CN00.1M" ...
#> $ geom    :sfc_GEOMETRY of length 15; first list element: List of 1
#> ..$ : num [1:1907, 1:2] -90.5 -90.5 -90.5 -90.5 -90.5 ...
#> ..- attr(*, "class")= chr [1:3] "XY" "POLYGON" "sfg"
#> - attr(*, "sf_column")= chr "geom"
#> - attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA
#> ..- attr(*, "names")= chr "uniqueID"

**Comment by michaeldorman** [comment]
Thanks! You are right, it's better to name the geometry column as `"geometry"` in agreement with `sf`. This is now changed in the development version:

```r
remotes::install_github("michaeldorman/nngeo")
```

please let me know if you still see any issue with this.
