### ISSUE TITLE
issue with nngeo data sets

### ISSUE THREAD

**Issue by DavidHine** [michaeldorman/nngeo#26]
Hi Michael
This package would be ideal for a problem I am trying to solve. 
I hope you progress it and add additional functionality/articulation of methods. For example, I would like to include more fields from the original data set, and have the columns labelled by their origin. 
My issue is that I get an error when running your code example. Running > nn = st_nn(cities, towns, progress = TRUE) produces this error message:
projected points
Error in if (!is.na(crs_units) & crs_units != "m") { : 
  argument is of length zero

I'd welcome your advice because having your example and its variants working would provide much needed insight. The proj string for those two data sets does not have a units comment.

**Comment by michaeldorman** [comment]
Hi David,

Thanks for your interest in the package! 

I can't reproduce the error message, for me this works:

```r
library(nngeo)
nn = st_nn(cities, towns, progress = TRUE)
nn
```

Could you please try to re-install `sf` and `nngeo`? Then, could you try the minimal example above, right after starting R? 

![image](https://user-images.githubusercontent.com/9386655/194059064-2ecfc7e6-f4c1-4561-a555-166fcfd8faa4.png)
