### ISSUE TITLE
large dataset with st_nn

### ISSUE THREAD

**Issue by riprobins** [michaeldorman/nngeo#27]
I have a spatial dataframe of 12million GPS locations, and I'm trying to find the nearest 4 neighbours to each event from a source of 2480 line segments.

Running this crashes my machine after about 15mins.  this is the code.

`nngeo::st_nn(events, segments, k = k, returnDist = TRUE, maxdist = 30, parallel = 10)`

are there limitations on st_nn or am I doing something wrong?

**Comment by michaeldorman** [comment]
There are no inherent limitations, other then (1) the computer's RAM size, and (2) the calculation time which may turn out to be impractical. 
1. Parallel computations "duplicate" the data for all processes, perhaps this leads to running out of RAM and therefore crashing. I'd try to use `parallel=1`, or `parallel=2`, and also track the state of RAM to confirm this. If so, then you can try `parallel=N`, where `N` is the largest value possible without running out of memory.
2. Also, I'd try to calculate the result for a subset of the data, e.g., the first 10K `events`, as in `nngeo::st_nn(events[1:10000,],segments,k=k,returnDist=TRUE,maxdist=30)`, and then estimate how much would it take to calculate for the entire 12M `events`. If the estimated time is impractical then you can try to simplify the data (see below), or use several computers, or switch to other software that may be faster (such as PostGIS).
3. If the segments are very short compared to the typical distances, then you can calculate segment centroids and calculate the nearest neighbors and distances with respect to the centroids. This will lose some of the information, however the calculation for point-point distances is much faster.

**Comment by riprobins** [comment]
Appreciate it, thanks.  In the end I've had to push the query to AWS and run on Athena.  The 12M events was the sample, the actual dataset is 200M
