### ISSUE TITLE
segfault 'memory not mapped' prevents installation

### ISSUE THREAD

**Issue by cjbwalsh** [michaeldorman/nngeo#28]
I am unable to install nngeo_0.4.7 (either from CRAN or github) in R 4.3.0 in ubuntu 22.04, getting the following error:
```
 *** caught segfault ***
address 0x55582a37ddb6, cause 'memory not mapped'
An irrecoverable exception occurred. R is aborting now ...
Segmentation fault (core dumped)
```
I have installed Rccp and RcppEigen via `apt install` (rather than `install.packages()` in R) from the [c2d4u](https://cran.r-project.org/bin/linux/ubuntu/) repository.  Perhaps this is causing a conflict?

**Comment by michaeldorman** [comment]
I couldn't reproduce the error, for me installation of `nngeo` version 0.4.7 works on Ubuntu 22.04 and R 4.3.0, tested both locally and in a cloud platform (DigitalOcean).

![Screenshot from 2023-04-30 15-23-30](https://user-images.githubusercontent.com/9386655/235352885-319e5615-3d9c-4acb-b51d-9eb5c8a529b0.png)

One suggestion that comes to mind is to use a different `gcc` version and/or settings. To do that, you can create a file `~/.R/Makevars`, with contents such as following, as also explained in the accepted answer [here](https://stackoverflow.com/questions/1616983/building-r-packages-using-alternate-gcc):

```sh
CC=gcc-11
CXX=g++-11
CFLAGS = -g -O2 -Wall -pedantic -Wstrict-prototypes
```

These settings are just an example; I don't know which exact settings you should use other than through trial and error. If you can please send the printout when installing the package (such as above) will try to think of something more specific.

**Comment by cjbwalsh** [comment]
Thanks Michael,
I tried a Makedir file as you suggested (and with `CC=gcc-11.3` and `CXX=g++-11.3`), but the installation fails with the same message, reproduced in full below (sorry for not doing that the first time).
```
> install.packages("nngeo")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/nngeo_0.4.7.tar.gz'
Content type 'application/x-gzip' length 476840 bytes (465 KB)
==================================================
downloaded 465 KB

* installing *source* package ‘nngeo’ ...
** package ‘nngeo’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
using C compiler: ‘gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0’
gcc -I"/usr/share/R/include" -DNDEBUG       -fpic  -g -O2 -ffile-prefix-map=/build/r-base-JhpCKt/r-base-4.3.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c dist.c -o dist.o
gcc -I"/usr/share/R/include" -DNDEBUG       -fpic  -g -O2 -ffile-prefix-map=/build/r-base-JhpCKt/r-base-4.3.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c geodesic.c -o geodesic.o
gcc -I"/usr/share/R/include" -DNDEBUG       -fpic  -g -O2 -ffile-prefix-map=/build/r-base-JhpCKt/r-base-4.3.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c nngeo_init.c -o nngeo_init.o
gcc -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -o nngeo.so dist.o geodesic.o nngeo_init.o -L/usr/lib/R/lib -lR
installing to /usr/local/lib/R/site-library/00LOCK-nngeo/00new/nngeo/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading

 *** caught segfault ***
address 0x558dbf6e21bc, cause 'memory not mapped'
An irrecoverable exception occurred. R is aborting now ...
Segmentation fault (core dumped)
ERROR: lazy loading failed for package ‘nngeo’
* removing ‘/usr/local/lib/R/site-library/nngeo’

The downloaded source packages are in
	‘/tmp/RtmpEawzv9/downloaded_packages’
Warning message:
In install.packages("nngeo") :
  installation of package ‘nngeo’ had non-zero exit status
> 
```

**Comment by michaeldorman** [comment]
Thanks! Sorry, I don't have any idea... This seems like a generic error message. 

P.S. I'm in a similar situation with a different program (`snx`, for VPN) which started to fail with `segmentation fault` a couple of weeks ago, interestingly - only on some of the machines with Ubuntu 22.04. Maybe this is an OS issue that will be solved in an update. (Hopefully! Because, same as your issue with `nngeo`, I don't have any idea how to solve it.)

**Comment by michaeldorman** [comment]
P.S. 2
One more thing that you can try is to install `nngeo` version 0.4.6. Just to rule out the possibility that the (very minor) change in the C code is causing the problem.

**Comment by cjbwalsh** [comment]
Good suggestion to try 0.4.6, but sadly the same result.   Many thanks for your consideration. I will wait patiently in hope for an OS update.
