### ISSUE TITLE
Clean output when progress = FALSE

### ISSUE THREAD

**Issue by latot** [michaeldorman/nngeo#29]
Hi, I notice if we try to use lat-lon and disable progress bar, we still will get output:

```R
ret <- nngeo::st_nn(
      points,
      nodes,
      returnDist = TRUE,
      k = k,
      progress = FALSE,
      parallel = cores
  )
lon-lat points
```

I think the best would be a way to disable that "lon-lat" message, maybe a new param for it? or if we disable progress is likely we want quiet output, so disable if is ```FALSE```.

Thx!

**Comment by michaeldorman** [comment]
Thanks for the suggestion! I believe that the distinction between lon-lat and projected data is important for the user, to be aware of what's going on (it's analogous to the way that `gstat` prints messages about the internally selected interpolation method). In cases where the messages are inconvenient I'd use `suppressMessages`:

```r
library(nngeo)
result = suppressMessages(st_nn(cities, towns, progress = FALSE))
```

**Comment by latot** [comment]
@michaeldorman There is several issues with that.

First, you are right, for ppl can be interested to know when is lon-lat, but only when you are working at the top level in R.

Here is where remove this message is an advantage:

For tests, is better have a clean result, we have several tools to pick the right errors and warnings like snapshot, if a library throws warning without be able to control it, causes to all the snapshots that uses it not be clear.

There is a main reason why don't supress warnings, is that we want to know the warnings, maybe we can hide this one, but we also want to know if in any time there is a new one, maybe you update something, maybe a dependency changed.

Due to this, is a lot better, be able to hide it, and with a new parameter.
