### ISSUE TITLE
Unary st_nn() -- eliminate self-neighboring

### ISSUE THREAD

**Issue by seasmith** [michaeldorman/nngeo#5]
`sf` has several functions with mixed argument behavior.  For example,  `st_union` and `st_intersection` accept either one or two spatial inputs. 

I think this would be of great benefit.

```r
# Example
library(nngeo)
data(towns)

head(st_nn(towns, k = 2, maxdist = 10e3))
# [[1]]
# [1]  93  5
# 
# [[2]]
# [1]  49
# 
# [[3]]
# [1]  42  8
# 
# [[4]]
# integer(0)
# 
# [[5]]
# [1]  12 93
# 
# [[6]]
# [1]  20 13
```

**Comment by michaeldorman** [comment]
Thanks Luke, this is an interesting suggestion!

It is true that `st_union` and `st_intersection` accept either one or two arguments. However, they have a special behavior with one argument, i.e., `st_union(x, x)` is not the same as `st_union(x)` and `st_intersection(x, x)` is not the same as `st_intersection(x)`. Therefore I'm not sure the `st_nn(x)` shortcut will not lead to confusion over simply using `st_nn(x, x)`. 

Currently this can be achieved with `st_nn(x, x, k = n + 1)`, followed by removing the first neighbor, which is always self:

```r
x = st_nn(towns, towns, k = 3, maxdist = 10e3)
# |======================================================================| 100%
x = sapply(x, "[", -1)
head(x)
# [[1]]
# [1] 93  5
# 
# [[2]]
# [1] 49
# 
# [[3]]
# [1] 42  8
# 
# [[4]]
# integer(0)
# 
# [[5]]
# [1] 12 93
# 
# [[6]]
# [1] 20 13
```

Will think about this.
