### ISSUE TITLE
How to speed up while using st_nn_pnt_geo.R

### ISSUE THREAD

**Issue by xiaguoxin** [michaeldorman/nngeo#6]
I got some longitude and latitude geo point data and found out it is very slow the st_nn() works on this kind of data, is there something I can do to make it more efficient?
I know I cannot use RANN::nn2() directly for this kind of data, but is there some kind of way to convert epsg 4326 to some projection that is good for use RANN::nn2()?
Thanks.

**Comment by michaeldorman** [comment]
1. Finding nearest neighbors in projected data can be done with `RANN` (which `nngeo` also uses). This is much faster than finding nearest neighbors in 4326. So, like you said, one solution would be to transform the points to a projected CRS. As long as the area of interest is small enough, most chances are that you can find an appropriate projection (UTM, for example). 
2. In case there is no suitable projection and you must keep the data in 4326, you can try one of the faster but less accurate distance metrics, such as the "Mapbox cheap ruler" provided in package `geodist` (https://cran.r-project.org/web/packages/geodist/index.html).
