### ISSUE TITLE
Distance vector to variable/column not available anymore (v0.3.0)

### ISSUE THREAD

**Issue by roboes** [michaeldorman/nngeo#8]
Hi,

I used the function st_nn to get the distance vector (class: units) to a variable/column, as follows.

`listings$distance_subway <- (st_nn(listings, subway_nyc, returnDist = TRUE))$dist`

I noticed that the above function stopped to work on nngeo v0.3.0.

I tried the following but it stored the vector as a list instead of units:

```
distance_subway <- st_nn(listings, subway_nyc, returnDist = TRUE)
listings$distance_subway <- distance_subway[[2]]
```

How to proceed?

**Comment by michaeldorman** [comment]
Hi,

The structure of the returned object from `st_nn(..., returnDist=TRUE)` was indeed changed. Now, the distances are also returned as a `list`, like the IDs, so that it will be easier to combine the IDs and distances if necessary. 

Starting from version 0.3.0, the distances can be extracted as a vector using `sapply(n[[2]], "[", 1)`, where `n` is the returned object from `st_nn` (using `k=1`). 

For example:

``` r
library(nngeo)
n = st_nn(towns[1:5, ], cities, returnDist = TRUE)
n
```

    ## [[1]]
    ## [[1]][[1]]
    ## [1] 3
    ## 
    ## [[1]][[2]]
    ## [1] 1
    ## 
    ## [[1]][[3]]
    ## [1] 3
    ## 
    ## [[1]][[4]]
    ## [1] 3
    ## 
    ## [[1]][[5]]
    ## [1] 3
    ## 
    ## 
    ## [[2]]
    ## [[2]][[1]]
    ## [1] 53071.5
    ## 
    ## [[2]][[2]]
    ## [1] 15069.49
    ## 
    ## [[2]][[3]]
    ## [1] 33345.18
    ## 
    ## [[2]][[4]]
    ## [1] 46392.06
    ## 
    ## [[2]][[5]]
    ## [1] 57459.81

``` r
dist = sapply(n[[2]], "[", 1)
dist
```

    ## [1] 53071.50 15069.49 33345.18 46392.06 57459.81

Sorry for the inconvenience.

Thanks and Best regards,

Michael

**Comment by roboes** [comment]
Dear Michael,

Thank you for your prompt reply. I noticed that similarly to your suggestion `sapply(n[[2]], "[", 1)`, the following code produces a similar outcome: `unlist(n[[2]])`. Both produce a numeric class object. But I actually wanted to insert these distance to a new column/variable inside a data.frame (as a vector). Do you know how to proceed?

Thank you in advance and best regards

**Comment by michaeldorman** [comment]
1. `unlist(n[[2]])` also works in case when using `st_nn` with `k=1` (which is the default). In case when `k` is >1, the expression `sapply(n[[2]], "[", 1)` will still return the distance to nearest, while `unlist(n[[2]])` will combine the distances from all `k` matches to one long vector which is probably not what you want.

2. Here is an example where the distances are inserted as a new column:

``` r
library(nngeo)
n = st_nn(towns, cities, returnDist = TRUE, progress = FALSE)
towns$dist = sapply(n[[2]], "[", 1)
towns
```

The `dist` column now contains the distance to nearest feature in `cities` for each feature in `towns`:

    ## Simple feature collection with 93 features and 2 fields
    ## geometry type:  POINT
    ## dimension:      XY
    ## bbox:           xmin: 34.3309 ymin: 30.96493 xmax: 35.83863 ymax: 33.17806
    ## epsg (SRID):    4326
    ## proj4string:    +proj=longlat +datum=WGS84 +no_defs
    ## First 10 features:
    ##                     geometry                    name     dist
    ## 1  POINT (35.54639 32.70683)                 ALUMMOT 53071.50
    ## 2  POINT (35.12573 31.65512)            ALLON SHEVUT 15069.49
    ## 3  POINT (35.18041 33.04801)                   AVDON 33345.18
    ## 4  POINT (35.48441 32.81265)                   ARBEL 46392.06
    ## 5   POINT (35.5824 32.66228) ASHDOT YA'AQOV(ME'UHAD) 57459.81
    ## 6  POINT (35.33804 32.85159)                  ARRABE 33249.05
    ## 7    POINT (35.25207 32.866)            ATSMON SEGEV 25841.51
    ## 8  POINT (35.22568 33.08865)                 ARAMSHA 39433.85
    ## 9   POINT (35.4369 31.67897)                  AVENAT 23358.34
    ## 10 POINT (34.90936 31.89039)                  AZARYA 24749.23

**Comment by dewoller** [comment]
Is this also the reason I can't get the distances when doing a st_join?  See example below:

``` r
library(nngeo)
#> Loading required package: sf
#> Linking to GEOS 3.6.2, GDAL 2.2.3, PROJ 4.9.3
data(cities)
data(towns)

cities = st_transform(cities, 32636)
towns = st_transform(towns, 32636)

st_nn(cities, towns, k=1, returnDist=TRUE)
#> [[1]]
#> [[1]][[1]]
#> [1] 29
#> 
#> [[1]][[2]]
#> [1] 18
#> 
#> [[1]][[3]]
#> [1] 69
#> 
#> 
#> [[2]]
#> [[2]][[1]]
#> [1] 7080.975
#> 
#> [[2]][[2]]
#> [1] 7240.91
#> 
#> [[2]][[3]]
#> [1] 12248.21

st_join( cities, towns, st_nn)
#> Simple feature collection with 3 features and 2 fields
#> geometry type:  POINT
#> dimension:      XY
#> bbox:           xmin: 668153.4 ymin: 3516889 xmax: 709644.2 ymax: 3630208
#> epsg (SRID):    32636
#> proj4string:    +proj=utm +zone=36 +datum=WGS84 +units=m +no_defs
#>      name.x    name.y                 geometry
#> 1 Jerusalem AMMINADAV POINT (709644.2 3516889)
#> 2  Tel-Aviv      AZOR POINT (668153.4 3551280)
#> 3     Haifa     ATLIT POINT (686303.6 3630208)
st_join( cities, towns, st_nn, k=1, returnDist=TRUE)
#> Error in rep(seq_len(nrow(x)), lengths(i)): invalid 'times' argument
```

<sup>Created on 2020-01-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by michaeldorman** [comment]
No, that wasn't possible before too. The `st_join` function expects a function that only returns the matching *indices*, not distances. I guess the reason is that distance is not always relevant for spatial join; for example, when the join function is `st_intersects` the distances between matching geometries are always zero. Therefore, joining only works when `st_nn` is passed with `returnDist=FALSE`, which is the default.

The distances can be added "manually" as follows:

``` r
library(nngeo)
data(cities)
data(towns)

# Join
cities = st_join(cities, towns, st_nn, k = 1)
cities

## Simple feature collection with 3 features and 2 fields
## geometry type:  POINT
## dimension:      XY
## bbox:           xmin: 34.78177 ymin: 31.76832 xmax: 35.21371 ymax: 32.79405
## epsg (SRID):    4326
## proj4string:    +proj=longlat +datum=WGS84 +no_defs
##      name.x    name.y                  geometry
## 1 Jerusalem AMMINADAV POINT (35.21371 31.76832)
## 2  Tel-Aviv      AZOR  POINT (34.78177 32.0853)
## 3     Haifa     ATLIT POINT (34.98957 32.79405)

# Get distances
n = st_nn(cities, towns, k = 1, returnDist = TRUE)
dist = sapply(n[[2]], "[", 1)
dist

## [1]  7080.092  7241.244 12247.989

# Bind distances to 'st_join' output
cities$dist = dist
cities

## Simple feature collection with 3 features and 3 fields
## geometry type:  POINT
## dimension:      XY
## bbox:           xmin: 34.78177 ymin: 31.76832 xmax: 35.21371 ymax: 32.79405
## epsg (SRID):    4326
## proj4string:    +proj=longlat +datum=WGS84 +no_defs
##      name.x    name.y                  geometry      dist
## 1 Jerusalem AMMINADAV POINT (35.21371 31.76832)  7080.092
## 2  Tel-Aviv      AZOR  POINT (34.78177 32.0853)  7241.244
## 3     Haifa     ATLIT POINT (34.98957 32.79405) 12247.989
```

The downside of the latter approach is that `st_nn` is executed twice: one time in `st_join` and another time to get the distances. Here is an alternative version where `st_nn` is run just once:

```r
data(cities)
data(towns)

# Get indices & distances
n = st_nn(cities, towns, k = 1, returnDist = TRUE)
ids = sapply(n[[1]], "[", 1)
dist = sapply(n[[2]], "[", 1)

# Join
cities = data.frame(cities, st_drop_geometry(towns)[ids, , drop = FALSE])
cities = st_sf(cities)

# Add distances
cities$dist = dist
cities

## Simple feature collection with 3 features and 3 fields
## geometry type:  POINT
## dimension:      XY
## bbox:           xmin: 34.78177 ymin: 31.76832 xmax: 35.21371 ymax: 32.79405
## epsg (SRID):    4326
## proj4string:    +proj=longlat +datum=WGS84 +no_defs
##        name    name.1                  geometry      dist
## 1 Jerusalem AMMINADAV POINT (35.21371 31.76832)  7080.092
## 2  Tel-Aviv      AZOR  POINT (34.78177 32.0853)  7241.244
## 3     Haifa     ATLIT POINT (34.98957 32.79405) 12247.989
```

**Comment by richardohrvall** [comment]
Thank you for a great package! I think you should consider adding the information in this last comment to the vignette of the package. I was wondering why it didn't work with returnDist in the st_join, and I think it's worth mentioning (unless it already is, and I was not reading carefully). And this workaround would probably be of interest to at least some users.
Best, Richard

**Comment by michaeldorman** [comment]
Hi Richard,

That's a good idea, thanks! I'll add the information to the vignette.

Best regards,

Michael

**Comment by michaeldorman** [comment]
https://github.com/michaeldorman/nngeo/commit/9d9b5429f7cd269948ded6cdf8504ce01b1e6534
